# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_BAIKAL) += bm1000-dbm.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm1000-mbm10.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm1000-mbm20.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bm1000-qemu-m.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bs1000-dbs.dtb
dtb-$(CONFIG_ARCH_BAIKAL) += bs1000-qemu-s.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
