# SPDX-License-Identifier: GPL-2.0-only
#
# 
#
# ccflags-$(CONFIG_ARCH_MMP) := -I$(srctree)/$(src)/include

#obj-$(CONFIG_PXA3xx)		+= mfp.o
#obj-$(CONFIG_ARCH_MMP)		+= mfp.o

#obj-$(CONFIG_PXA_SSP)		+= ssp.o

obj-$(CONFIG_UNA10)       += una10.o
